require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'
Metrics/LineLength:
  Max: 150
Metrics/ModuleLength:
  Max: 200
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/ClassLength:
  Max: 150
Style/FormatStringToken:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false
Lint/AmbiguousOperator:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
