version: "3"
services:
  postgres:
    image: postgres:10.5
    container_name: postgres
    env_file:
      - docker.postgres.env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
    external: true