version: "3"
services:
  boilerplate_app:
    image: boilerplate-app:latest
    build: ../
    container_name: boilerplate-app
    command: app
    env_file:
      - docker.app.env
    volumes:
      - app-public:/var/www/boilerplate-app/public/uploads:z
      - app-log:/var/www/boilerplate-app/log:z
    ports:
      - "127.0.0.1:3000:9292"
    networks:
      - backend
  
volumes:
  app-log:
  app-public:

networks:
  backend:
    external: true