version: "3.3"
services:
  boilerplate_app:
    image: boilerplate-app:latest
    build: ../
    container_name: boilerplate-app
    command: bundle exec puma --config /var/www/boilerplate-app/docker/scripts/puma.rb
    env_file:
      - docker.env
    volumes:
      - app-public:/var/www/boilerplate-app/public:z
      - app-log:/var/www/boilerplate-app/log:z
    ports:
      - 3000:3000

  boilerplate_sidekiq:
    image: boilerplate-app:latest
    build: ../
    container_name: boilerplate-sidekiq
    command: bundle exec sidekiq
    environment:
      REDIS_URL: redis://redis:6379/0

  postgres:
    image: postgres:10.5
    container_name: postgres
    env_file:
      - docker.env
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:5.0-alpine
    command: redis-server
    volumes:
      - redis-data:/data

volumes:
  app-log:
  app-public:
  db-data:
  redis-data:
