default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>

development:
  <<: *default
  database: rails-api-boilerplate_development

test:
  <<: *default
  database: rails-api-boilerplate_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "rails-api-boilerplate_production" } %>
